package entornos_Desarrollo_Base_de_Datos;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Alumnos.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Alumnos implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Num_Alum. */
	private Long numAlum;

	/** Nombre. */
	private String nombre;

	/** Grupo. */
	private String grupo;

	/** The set of Cursan. */
	private Set<Cursan> cursanSet;

	/** The set of Hacen. */
	private Set<Hacen> hacenSet;

	/** The set of Realizan. */
	private Set<Realizan> realizanSet;

	/**
	 * Constructor.
	 */
	public Alumnos() {
		this.cursanSet = new HashSet<Cursan>();
		this.hacenSet = new HashSet<Hacen>();
		this.realizanSet = new HashSet<Realizan>();
	}

	/**
	 * Set the Num_Alum.
	 * 
	 * @param numAlum
	 *            Num_Alum
	 */
	public void setNumAlum(Long numAlum) {
		this.numAlum = numAlum;
	}

	/**
	 * Get the Num_Alum.
	 * 
	 * @return Num_Alum
	 */
	public Long getNumAlum() {
		return this.numAlum;
	}

	/**
	 * Set the Nombre.
	 * 
	 * @param nombre
	 *            Nombre
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * Get the Nombre.
	 * 
	 * @return Nombre
	 */
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Set the Grupo.
	 * 
	 * @param grupo
	 *            Grupo
	 */
	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

	/**
	 * Get the Grupo.
	 * 
	 * @return Grupo
	 */
	public String getGrupo() {
		return this.grupo;
	}

	/**
	 * Set the set of the Cursan.
	 * 
	 * @param cursanSet
	 *            The set of Cursan
	 */
	public void setCursanSet(Set<Cursan> cursanSet) {
		this.cursanSet = cursanSet;
	}

	/**
	 * Add the Cursan.
	 * 
	 * @param cursan
	 *            Cursan
	 */
	public void addCursan(Cursan cursan) {
		this.cursanSet.add(cursan);
	}

	/**
	 * Get the set of the Cursan.
	 * 
	 * @return The set of Cursan
	 */
	public Set<Cursan> getCursanSet() {
		return this.cursanSet;
	}

	/**
	 * Set the set of the Hacen.
	 * 
	 * @param hacenSet
	 *            The set of Hacen
	 */
	public void setHacenSet(Set<Hacen> hacenSet) {
		this.hacenSet = hacenSet;
	}

	/**
	 * Add the Hacen.
	 * 
	 * @param hacen
	 *            Hacen
	 */
	public void addHacen(Hacen hacen) {
		this.hacenSet.add(hacen);
	}

	/**
	 * Get the set of the Hacen.
	 * 
	 * @return The set of Hacen
	 */
	public Set<Hacen> getHacenSet() {
		return this.hacenSet;
	}

	/**
	 * Set the set of the Realizan.
	 * 
	 * @param realizanSet
	 *            The set of Realizan
	 */
	public void setRealizanSet(Set<Realizan> realizanSet) {
		this.realizanSet = realizanSet;
	}

	/**
	 * Add the Realizan.
	 * 
	 * @param realizan
	 *            Realizan
	 */
	public void addRealizan(Realizan realizan) {
		this.realizanSet.add(realizan);
	}

	/**
	 * Get the set of the Realizan.
	 * 
	 * @return The set of Realizan
	 */
	public Set<Realizan> getRealizanSet() {
		return this.realizanSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((numAlum == null) ? 0 : numAlum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Alumnos other = (Alumnos) obj;
		if (numAlum == null) {
			if (other.numAlum != null) {
				return false;
			}
		} else if (!numAlum.equals(other.numAlum)) {
			return false;
		}
		return true;
	}

}
