package entornos_Desarrollo_Base_de_Datos;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Profesores.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Profesores implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Nombre. */
	private String nombre;

	/** Num_prof. */
	private Long numProf;

	/** The set of Asignaturas. */
	private Set<Asignaturas> asignaturasSet;

	/** The set of Elaboran. */
	private Set<Elaboran> elaboranSet;

	/**
	 * Constructor.
	 */
	public Profesores() {
		this.asignaturasSet = new HashSet<Asignaturas>();
		this.elaboranSet = new HashSet<Elaboran>();
	}

	/**
	 * Set the Nombre.
	 * 
	 * @param nombre
	 *            Nombre
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * Get the Nombre.
	 * 
	 * @return Nombre
	 */
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Set the Num_prof.
	 * 
	 * @param numProf
	 *            Num_prof
	 */
	public void setNumProf(Long numProf) {
		this.numProf = numProf;
	}

	/**
	 * Get the Num_prof.
	 * 
	 * @return Num_prof
	 */
	public Long getNumProf() {
		return this.numProf;
	}

	/**
	 * Set the set of the Asignaturas.
	 * 
	 * @param asignaturasSet
	 *            The set of Asignaturas
	 */
	public void setAsignaturasSet(Set<Asignaturas> asignaturasSet) {
		this.asignaturasSet = asignaturasSet;
	}

	/**
	 * Add the Asignaturas.
	 * 
	 * @param asignaturas
	 *            Asignaturas
	 */
	public void addAsignaturas(Asignaturas asignaturas) {
		this.asignaturasSet.add(asignaturas);
	}

	/**
	 * Get the set of the Asignaturas.
	 * 
	 * @return The set of Asignaturas
	 */
	public Set<Asignaturas> getAsignaturasSet() {
		return this.asignaturasSet;
	}

	/**
	 * Set the set of the Elaboran.
	 * 
	 * @param elaboranSet
	 *            The set of Elaboran
	 */
	public void setElaboranSet(Set<Elaboran> elaboranSet) {
		this.elaboranSet = elaboranSet;
	}

	/**
	 * Add the Elaboran.
	 * 
	 * @param elaboran
	 *            Elaboran
	 */
	public void addElaboran(Elaboran elaboran) {
		this.elaboranSet.add(elaboran);
	}

	/**
	 * Get the set of the Elaboran.
	 * 
	 * @return The set of Elaboran
	 */
	public Set<Elaboran> getElaboranSet() {
		return this.elaboranSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((numProf == null) ? 0 : numProf.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Profesores other = (Profesores) obj;
		if (numProf == null) {
			if (other.numProf != null) {
				return false;
			}
		} else if (!numProf.equals(other.numProf)) {
			return false;
		}
		return true;
	}

}
